import React from 'react';
import styled from 'styled-components';
import { useMetaTags } from '../hooks/useMetaTags';

const TermsPage = () => {
  useMetaTags('TzStats Terms of Service', '', '');
  return (
    <Policy>
      <h1 id="terms-of-service">Terms of Service</h1>
      <p><em>last revised: Feburary 14, 2020</em></p>
      <h3 id="abstract">Abstract</h3>
      <p>TzStats.com is a public information website displaying publicly available data and aggregate statistics about the Tezos blockchain. TzStats is developed and operated by Blockwatch Data Inc. and provided to you free of charge.</p>
      <p>Data available via the TzStats API is subject to the Creative Commons Attribution-NonCommercial License <strong>CC BY-NC 4.0</strong>. All information is displayed <em>as is</em> and we provide no guarantee for correctness or fitness for a particular purpose. Information does not constitute investment advice, financial advice, trading advice, or any other sort of advice. We disclaim any responsibility for any missing or wrong information. You understand that you are using any and all information available here at your own risk.</p>
      <p>If you wish to use the API for commercial projects you need to obtain a separate commercial license from Blockwatch Data Inc. Please contact us at <a href="license@blockwatch.cc">license@blockwatch.cc</a> for details.</p>
      <h3 id="terms">Terms</h3>
      <p>Thank you for using TzStats.com (the “Website”). This page contains the terms that apply to your use of the Website (the “Terms”).  The Site is owned and operated by Blockwatch Data Inc. (“Blockwatch,” “we,” or “us”). Blockwatch offers a structured set of data, text, and media files that includes public data from the Tezos blockchain, cryptocurrency markets and other data (the “Data”). The Data is provided through the Site, mobile applications, API, data exports and widgets (collectively, the “Platform,” and together with the Data, the “Services”).</p>
      <p>These Terms of Service govern your use of the Site and the Services, and may be updated by us from time to time without notice to you. Please read these Terms of Service carefully before using the Site and the Services. By accessing or using the Site or the Services, you acknowledge that you have read, understood, and agree to be legally bound by the terms and conditions of these Terms of Service and the terms and conditions of our <a href="/privacy">Privacy Policy</a>, which is hereby incorporated by reference (collectively with these Terms of Service, this “Agreement”). If you do not agree to any of these terms, then please do not access or use the Site or the Services.</p>
      <p>Commercial and academic use of the Data are subject to additional terms governing the use of the Data.</p>
      <p>THE SECTIONS BELOW TITLED “BINDING ARBITRATION” AND “CLASS ACTION WAIVER” CONTAIN A BINDING ARBITRATION AGREEMENT AND CLASS ACTION WAIVER.  THEY AFFECT YOUR LEGAL RIGHTS.  PLEASE READ THEM.</p>
      <h3 id="visitors-and-registered-users">Visitors and Registered Users</h3>
      <p>We provide Visitors and Registered Users with access to the Site and Services as described below.  </p>
      <p><strong>Visitors.</strong>  Visitors, as the term implies, are people who do not register with us, but want to explore the Site.  No login is required for Visitors.  Visitors can: (i) view all publicly-available content on the Site; and (ii) e-mail us.</p>
      <p><strong>Registered Users.</strong>  Registered Users are individuals that have created a registered account on the Site. Registered Users can do all the things that Visitors can do, and: (i) create, access, manage, and update their own personal accounts on the Site; (ii) post User Content (as defined below) on the Site; (iii) sign up for alerts and other notifications; and (iv) if you have entered into a separate Master Services Agreement (“MSA“) with Blockwatch, receive access to certain additional Services as may be set forth in the MSA.</p>
      <p>Blockwatch is under no obligation to accept any individual as a Registered User and may accept or reject any registration in its sole and complete discretion.  In addition, Blockwatch may deactivate or suspend any account at any time, including, without limitation, if it determines that a Registered User has violated this Agreement. We reserve the right, in our sole and absolute discretion, to deny you access to the Site, or any portion of the Site, without notice and without reason.  In the event of any conflict between the terms and conditions of this Agreement and the terms and conditions of an MSA between you and Blockwatch, the terms and conditions of the MSA shall control.</p>
      <h3 id="access-to-the-services">Access to the Services</h3>
      <p>Subject to the terms and conditions of these Terms of Service, Blockwatch may provide access to the Services in a number of ways, including, but not be limited to, the offering of any materials displayed or performed on the Site and related features (including, but not limited to text, data, software, graphics, photographs, images, illustrations, audio clips and video clips), copying Content directly from the Site, through export data files or other data dumps directly from Blockwatch, or through the TzStats API (which will enable you to build applications on top of the Platform). Blockwatch may change, suspend or discontinue the Services for any reason, at any time, including the availability of any feature or Content. Blockwatch may also restrict your access to parts or all of the Services without notice or liability.</p>
      <p>Blockwatch will use reasonable efforts to ensure that the Platform is available twenty-four hours a day, seven days a week. However, there will be occasions when the Services will be interrupted for Platform maintenance, upgrades and emergency repairs or due to failure of telecommunications links and equipment.</p>
      <h3 id="prohibited-uses">Prohibited Uses</h3>
      <p>You shall not post, transmit, redistribute, upload, or promote any communications, content or materials that (a) contain corrupted files, viruses, or any other similar software files, the intent of which is to damage the operation of another&#39;s computer; (b) are unlawful, threatening, harassing, abusive, defamatory, invasive of privacy or publicity rights, vulgar, obscene, sexually explicit, hateful, profane, indecent, racially or ethnically derogatory, or otherwise objectionable; (c) contain chain letters or pyramid schemes; (d) contain any unsolicited advertising, promotional materials, or other forms of solicitation to other users, individuals or entities; (e) include any information that references other websites or any sensitive or personal information, including personal e-mail addresses, postal addresses, phone numbers, credit card information, or any similar information; (f) impersonate any person, business or entity, including our company and our employees and agents; (g) encourage conduct that would constitute a criminal offense; (h) give rise to civil liability; (i) otherwise violate any law (including, but not limited to, those governing consumer protection, unfair competition, anti-discrimination or false advertising); or (j) in doing so, amounts to any conduct that, in our judgment, restricts, impairs, interferes or inhibits any other user from using or enjoying, or is otherwise detrimental to, the Site or the Services.</p>
      <p>You shall not use automated means, including spiders, robots, crawlers, data mining tools, or the like to download data from the Site. You may not bypass any measures used by Blockwatch to prevent or restrict access to the Site. Any unauthorized use by you shall terminate the permission granted to you by Blockwatch to use and access the Site and the Services.</p>
      <p>In addition, you agree that:</p>
      <ul>
      <li>You will not access or use the Site or the Services to collect any market research for a competing business;</li>
      <li>You will not trade, sell, rent, loan, lease or license any Content or access to the Service, whether commercially or free of charge;</li>
      <li>You will not cover, obscure, block, or in any way interfere with any safety features on the Site or the Services;</li>
      <li>You will not solicit personal information from any person under the age of 18;</li>
      <li>You will not solicit passwords or personal information for commercial or unlawful purposes;</li>
      <li>You will not take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our technical infrastructure;</li>
      <li>You will not interfere with or attempt to interrupt the proper operation of the Site or the Services through the use of any virus, device, information collection or transmission mechanism, software or routine, or access or attempt to gain access to any data, files, or passwords related to the Site or the Services through hacking, password or data mining, or any other means; and</li>
      <li>You will not use the Site or the Services for any malicious activity, as determined by Blockwatch in its sole and absolute discretion.</li>
      </ul>
      <h3 id="use-of-the-data">Use of the Data</h3>
      <h4 id="non-commercial-use">NON-COMMERCIAL USE</h4>
      <p>As of the date of this Agreement, Blockwatch grants you a license to use the Data that is explicitly marked as public, the “Public Data“, in accordance with the Creative Commons Attribution-NonCommercial License <strong>CC BY-NC 4.0</strong> (the “Creative Commons License”), the terms and conditions of which are incorporated here by this reference. The Creative Commons License can be found at <a href="https://creativecommons.org/licenses/by-nc/4.0/legalcode">https://creativecommons.org/licenses/by-nc/4.0/legalcode</a>.</p>
      <p>Under the Creative Commons License, you are free to adapt and share the Public Data for noncommercial purposes, but if you do so you must:</p>
      <ul>
      <li>(i) give Blockwatch and TzStats appropriate credit,</li>
      <li>(ii) provide a link to the source material on the Site,</li>
      <li>(iii) provide a link to the Creative Commons License, and</li>
      <li>(iv) indicate if changes were made to the Public Data ((i)-(iv) collectively, “Attribution”).</li>
      </ul>
      <p>Attribution allows others to correct errors and keep the Public Data current. You may give Attribution in any reasonable manner, but not in any way that suggests that Blockwatch or TzStats endorses you or your use. A reasonable way is, for example, to include a note reading “Data provided by Blockwatch on TzStats.com“ together with a hyperlink to <a href="https://tzstats.com">https://tzstats.com</a>.</p>
      <p>You are solely responsible for your compliance with the Creative Commons License whenever you use or reuse the Public Data. If you have any questions regarding Attribution, you can contact us at <a href="mailto:license@blockwatch.cc">license@blockwatch.cc</a>.</p>
      <h4 id="commercial-use">COMMERCIAL USE</h4>
      <p>If you wish to use the Data in a manner that is primarily intended for or directed towards commercial advantage or monetary compensation (such use, “Commercial Use”), Blockwatch requires that you enter into a separate commercial license agreement. Entering into a separate commercial license allows us to protect Blockwatch’s investment in the Data and to maintain the integrity of the Data.</p>
      <p>Please contact us at <a href="mailto:license@blockwatch.cc">license@blockwatch.cc</a> for more information about Commercial Uses of our Data.</p>
      <h4 id="academic-use">ACADEMIC USE</h4>
      <p>If you are a researcher, lecturer or student affiliated with an accredited university or research institute and wish to use the Data for research and educational purposes, Blockwatch offers a separate academic license agreement. Entering into a separate academic license allows us to better tailor your use of the Data to academic work and publication standards and helps us to maintain the quality of the Data.</p>
      <p>Please contact us at <a href="mailto:license@blockwatch.cc">license@blockwatch.cc</a> for more information about Academic Uses of our Data.</p>
      <h3 id="intellectual-property">Intellectual Property</h3>
      <p>Blockwatch retains all right, title and interest in and to the Services, all software and technology incorporated therein, and all content made available to you through the Services (other than User Content (as defined below)). The design of the Site and all text, graphics, information, content, product design, and other material displayed on or that can be downloaded from the Site (collectively, the “Content”) belongs to us. The Blockwatch and TzStats names and logos displayed on the Site (the “Blockwatch IP”) are Blockwatch’s sole and exclusive property. Except as expressly set forth in these Terms of Service, you have no right in or to the Blockwatch IP. Other company or product names and logos used and displayed on the Site are trademarks of their respective owners. Nothing on the Site should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of the Blockwatch IP or other trademarks displayed on the Site, without our written permission or the written permission of the owner of the trademark, as the case may be. Any unauthorized use of the Content, Blockwatch IP or the trademarks of others may violate copyright laws, trademark laws, laws of privacy and publicity, and other laws and regulations and is prohibited. In the event of a violation, we reserve the right to seek all remedies available at law and/or in equity.</p>
      <h3 id="user-content">User Content</h3>
      <p>You may provide, create or modify content in or to the Services, including making updates to existing content on the Data or adding new content to the Data (hereinafter, “User Content“). If you do so, you affirm, represent, and warrant that: (i) the User Content is original; (ii) you own all right, title and interest in and to the User Content and have the sole and exclusive right (including all intellectual property and other proprietary rights embodied by the User Content or represented by such User Content) to license all of the rights therein to us as set forth below; (iii) use of your User Content by us in accordance with the license granted below will not infringe upon or misappropriate the rights of any third party including, without limitation, any intellectual property or privacy rights; and (iv) you have obtained written permission from any other person named, photographed or otherwise depicted or whose voice is used in your User Content which will allow us to utilize the User Content without compensation to any third party. We do not permit copyright infringing activities on the Site, and we may remove any User Content in our sole discretion.</p>
      <p>By providing any User Content, you hereby grant to Blockwatch an unrestricted, nonexclusive, perpetual, royalty-free, worldwide, transferable and irrevocable license and right with the right to sublicense through multiple tiers of sub-licensees, to use, edit, alter, copy, reproduce, disclose, display, publish, remove, prepare derivative works from, perform, distribute, exhibit, broadcast, or otherwise exploit such User Content, in whole or in part, in any form, media or technology, now known or hereafter developed. Under the license granted by you to Blockwatch herein, we shall be free to use any ideas or concepts contained in any User Content as set forth herein without further attribution, compensation or notice to you. We reserve the right to delete or remove any User Content in our sole discretion.</p>
      <p>Blockwatch owns all rights, title, and interests in intellectual property rights in any contributions by its employees, any derivative works developed by Blockwatch and the compilations and collective works in the Data, including those works incorporating User Content (but not rights to User Content by itself).</p>
      <h3 id="your-account">Your Account</h3>
      <p>You may choose to create an account at the Site (an “Account”). In order to do so, you will have to provide your email address as username, a password, and certain information about yourself. To protect your Account, you should choose a password different than names, birthdays, or street addresses associated with you. You agree that you will provide complete, current and accurate information about yourself as requested, and that you will keep that information up to date. You are responsible for maintaining the confidentiality of your password and for restricting access to your computer, and agree not to disclose your password to a third party. You are solely responsible for all activities that occur under your Account or with your password.</p>
      <h3 id="communications-with-us">Communications with Us</h3>
      <p>With respect to all e-mails and communications you send to us, including, but not limited to, feedback, questions, comments, suggestions, and the like, we shall be free to use any ideas, concepts, know-how, or techniques contained in your communications for any purpose whatsoever, including but not limited to, the development, production, and marketing of products and services that incorporate such information without compensation or attribution to you.</p>
      <h3 id="third-party-sites">Third Party Sites</h3>
      <p>Periodically, links may be established from the Site to external websites or content (including, but not limited to, photographs, graphics, pictures, text, articles, designs, video, music, sound, information, applications, and software) operated by third parties (each, a “Third Party Site“). These links to Third Party Sites are provided for your convenience only and do not imply that we endorse any Third Party Site or any content therein. We do not control and we are not responsible or liable for any Third Party Site or any content, advertising, products, or other materials on or available from any Third Party Site. Access to a Third Party Site is at your own risk, and we will have no liability for any damages or loss caused or alleged to be caused by or in connection with any purchase, use of or reliance on any content, goods, or services available on or through any Third Party Site.</p>
      <h3 id="personal-information">Personal Information</h3>
      <p>Any personal information that you provide to us through your use of the Site is subject to the terms of our <a href="/privacy">Privacy Policy</a>, which is hereby incorporated by reference in its entirety.</p>
      <h3 id="copyright-owners">Copyright Owners</h3>
      <p>Blockwatch is an database provider and the Data, including but not limited to database schema, text, media content, and data, is protected by copyrights, trademarks, service marks, international treaties, and/or other proprietary rights and laws of the United States and other countries. The Data has been developed, compiled, prepared, revised, selected and arranged by Blockwatch and others, and is as such also protected as a collective work or compilation under US copyright and other laws and treaties.</p>
      <p>All Public data in our databases is a direct copy of data published on various locations on the Internet and on the public Tezos blockchain. Like a search engine, Blockwatch makes no claim to own the public data it indexes or caches. Blockwatch endeavors to respect copyright. If you believe this site is indexing your copyright data and you would rather it not do so, you may submit a request to delete to <a href="mailto:copyright@blockwatch.cc">copyright@blockwatch.cc</a>.</p>
      <h3 id="notice-of-copyright-infringement">Notice of Copyright Infringement</h3>
      <p>If you are a copyright owner or an agent thereof and believe that any Content infringes upon your copyrights, you may notify us by providing the following information in writing:</p>
      <ul>
      <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed;</li>
      <li>Identification of the location where the original or an authorized copy of the copyrighted work exists;</li>
      <li>Identification of the User Content or other Content that is claimed to be infringing and a description of the infringing activity and information reasonably sufficient to permit us to locate the same;</li>
      <li>Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and, if available, an email address;</li>
      <li>A statement that you have a good faith belief that use of the User Content or other Content in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
      <li>A statement that the information in the notification is accurate, and, under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed.</li>
      </ul>
      <p>Our agent for notice of claims of copyright infringement can be reached as follows:</p>
      <pre><code>
      Copyright Agent<br/>
      Blockwatch Data Inc.<br/>
      61 Greenpoint Ave, Suite 693<br/>
      Brooklyn, NY 11222<br/>
      copyright@blockwatch.cc
      </code></pre><p>You acknowledge that if you fail to comply with all of the requirements above, your notice may not be valid.</p>
      <h2 id="disclaimers">Disclaimers</h2>
      <h3 id="no-investment-advice">No Investment Advice</h3>
      <p>The information provided on this website does not constitute investment advice, financial advice, trading advice, or any other sort of advice and you should not treat any of the website&#39;s content as such. Blockwatch does not recommend that any cryptocurrency should be bought, sold, or held by you. Do conduct your own due diligence and consult your financial advisor before making any investment decisions.</p>
      <h3 id="limitation-of-liability">Limitation of Liability</h3>
      <p>YOU ACKNOWLEDGE THAT BLOCKWATCH DOES NOT REPRESENT OR WARRANT THAT THE DATA, CONTENT, OR ANY OTHER INFORMATION PROVIDED THROUGH THE SITE OR SERVICES WILL BE ACCURATE OR COMPLETE.  </p>
      <p>YOU ALSO ACKNOWLEDGE THAT THE SITE AND/OR SERVICES MAY CONTAIN BUGS, ERRORS, AND OTHER PROBLEMS THAT COULD CAUSE SYSTEM FAILURES. CONSEQUENTLY, THE SITE, THE SERVICES, AND THE CONTENT ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT ANY WARRANTIES OF ANY KIND, INCLUDING THAT THE SITE, THE SERVICES, OR THE CONTENT WILL OPERATE ERROR-FREE OR THAT THE SITE, THE SERVICES, ITS SERVERS, OR THE CONTENT ARE FREE OF COMPUTER VIRUSES OR SIMILAR CONTAMINATION OR DESTRUCTIVE FEATURES.</p>
      <p>WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF TITLE, MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES’ RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE AND ANY WARRANTIES ARISING FROM A COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE.  </p>
      <p>IN CONNECTION WITH ANY WARRANTY, CONTRACT, OR COMMON LAW TORT CLAIMS: (I) WE AND OUR LICENSORS SHALL NOT BE LIABLE FOR ANY INCIDENTAL OR CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION RESULTING FROM THE USE OR INABILITY TO ACCESS AND USE THE SITE, THE SERVICES, OR THE CONTENT, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; AND (II) ANY DIRECT DAMAGES THAT YOU MAY SUFFER AS A RESULT OF YOUR USE OF THE SITE, THE SERVICES, OR THE CONTENT SHALL BE LIMITED TO THE HIGHER OF FIFTY DOLLARS ($50) OR THE TOTAL FEES THAT YOU HAVE PAID TO US WITHIN THE SIX (6) MONTHS IMMEDIATELY PRECEDING THE EVENTS GIVING RISE TO ANY CLAIM.  </p>
      <p>NOTHING IN THESE TERMS OF USE SHALL AFFECT ANY NON-WAIVABLE STATUTORY RIGHTS THAT APPLY TO YOU.</p>
      <h3 id="indemnification">Indemnification</h3>
      <p>You agree to defend, indemnify and hold Blockwatch harmless from and against any and all claims, losses, liabilities and expenses (including, without limitation, attorneys’ fees) arising from or relating to (i) any User Content made by you; (ii) your misuse of the Site, the Services or any Content; (iii) breach by you of these Terms of Service; or (iv) your violation of any third-party rights, including without limitation any copyright, trademark, property, publicity, or privacy right.</p>
      <h3 id="revisions-to-these-terms-of-service">Revisions to these Terms of Service</h3>
      <p>We may revise these Terms of Service at any time and from time to time and will post the revised Terms of Service on the Site. Your continued use of the Site after any revisions to these Terms of Service are posted will be considered acceptance by you of those changes. We encourage you to visit this page from time to time to review the then current Terms of Service.</p>
      <h3 id="termination">Termination</h3>
      <p>You or we may suspend or terminate your Account and/or your use of the Site or Services at any time, for any reason or for no reason. You are personally liable for any charges incurred prior to termination. We reserve the right to change, suspend, or discontinue all or any aspect of the Site or the Services at any time without notice.</p>
      <h3 id="binding-arbitration">Binding Arbitration</h3>
      <p>In the event of a dispute arising under or relating to this Agreement, the Site, or the Services (each, a “Dispute”), either party may elect to finally and exclusively resolve the dispute by binding arbitration governed by the Federal Arbitration Act (“FAA”). Any election to arbitrate, at any time, shall be final and binding on the other party. IF EITHER PARTY CHOOSES ARBITRATION, NEITHER PARTY SHALL HAVE THE RIGHT TO LITIGATE SUCH CLAIM IN COURT OR TO HAVE A JURY TRIAL, EXCEPT EITHER PARTY MAY BRING ITS CLAIM IN ITS LOCAL SMALL CLAIMS COURT, IF PERMITTED BY THAT SMALL CLAIMS COURT RULES AND IF WITHIN SUCH COURT’S JURISDICTION.  ARBITRATION IS DIFFERENT FROM COURT, AND DISCOVERY AND APPEAL RIGHTS MAY ALSO BE LIMITED IN ARBITRATION.  All disputes will be resolved before a neutral arbitrator selected jointly by the parties, whose decision will be final, except for a limited right of appeal under the FAA. The arbitration shall be commenced and conducted by JAMS pursuant to its then current Comprehensive Arbitration Rules and Procedures and in accordance with the Expedited Procedures in those rules, or, where appropriate, pursuant to JAMS’ Streamlined Arbitration Rules and Procedures. All applicable JAMS’ rules and procedures are available at the JAMS website www.jamsadr.com. Each party will be responsible for paying any JAMS filing, administrative, and arbitrator fees in accordance with JAMS rules.  Judgment on the arbitrator’s award may be entered in any court having jurisdiction. This clause shall not preclude parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.  The arbitration may be conducted in person, through the submission of documents, by phone, or online. If conducted in person, the arbitration shall take place in the United States county where you reside. The parties may litigate in court to compel arbitration, to stay a proceeding pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.  The parties shall cooperate in good faith in the voluntary and informal exchange of all non-privileged documents and other information (including electronically stored information) relevant to the Dispute immediately after commencement of the arbitration. As set forth in Section ”Equitable Relief” below, nothing in this Agreement will prevent us from seeking injunctive relief in any court of competent jurisdiction as necessary to protect our proprietary interests.</p>
      <h3 id="class-action-waiver">Class Action Waiver</h3>
      <p>You agree that any arbitration or proceeding shall be limited to the Dispute between us and you individually. To the full extent permitted by law, (i) no arbitration or proceeding shall be joined with any other; (ii) there is no right or authority for any Dispute to be arbitrated or resolved on a class action-basis or to utilize class action procedures; and (iii) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons. YOU AGREE THAT YOU MAY BRING CLAIMS AGAINST US ONLY IN YOUR INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.</p>
      <h3 id="equitable-relief">Equitable Relief</h3>
      <p>You acknowledge and agree that in the event of a breach or threatened violation of our intellectual property rights and confidential and proprietary information by you, we will suffer irreparable harm and will therefore be entitled to injunctive relief to enforce this Agreement.  We may, without waiving any other remedies under this Agreement, seek from any court having jurisdiction any interim, equitable, provisional, or injunctive relief that is necessary to protect our rights and property pending the outcome of the arbitration referenced above.  You hereby irrevocably and unconditionally consent to the personal and subject matter jurisdiction of the federal and state courts in the State of New York, Borough of Manhattan for purposes of any such action by us.</p>
      <h3 id="controlling-law">Controlling Law</h3>
      <p>The Agreement and any action related thereto will be governed by the laws of the State of New York without regard to its conflict of laws provisions.  The Parties hereby consent and agree to the exclusive jurisdiction of the state and federal courts located in the State of New York, Borough of Manhattan for all suits, actions, or proceedings directly or indirectly arising out of or relating to this Agreement, and waive any and all objections to such courts, including but not limited to, objections based on improper venue or inconvenient forum, and each party hereby irrevocably submits to the exclusive jurisdiction of such courts in any suits, actions, or proceedings arising out of or relating to this Agreement.</p>
      <h3 id="miscellaneous">Miscellaneous</h3>
      <p>The sections of these Terms of Service entitled Intellectual Property, Disclaimers, Limitation of Liability, Indemnification, Controlling Law, Binding Arbitration, Class Action Waiver, Equitable Relief, and Miscellaneous shall survive the termination of these Terms of Service. The paragraph headings herein are provided only for reference and shall have no effect on the construction or interpretation of these Terms of Service. You expressly absolve and release Blockwatch from any claim of harm resulting from a cause beyond their control, including, but not limited to, failure of electronic or mechanical equipment or communication lines, telephone or other interconnect problems, computer viruses, unauthorized access, theft, operator errors, severe weather, earthquakes, or natural disasters, strikes or other labor problems, wars, terrorist activities or governmental restrictions. You may not assign these Terms of Service.No waiver shall be effective unless in writing. Neither the course of conduct between parties nor trade practice shall act to modify any provision of these Terms of Service. These Terms of Service contain the entire agreement of the parties concerning the subject matter and supersedes all existing agreements and all other oral, written or other communication between the parties. You will comply with all laws, rules and regulations which are now or hereinafter promulgated by any government authority or agency which govern or apply to the operation and use of the Site, or any Content. You agree to transact with us and receive all notices electronically. We will provide notices by posting them on the Site, or, in some cases, we may provide notice by email to users with Accounts. To receive electronic notices, you must have access to the Internet, an Internet browser that can access the Site and/or access to the email address you provided to us. You will need a printer attached to your personal computer to print any notices. You can retrieve an electronic copy and a printable version of the Terms of Service by clicking on the “Terms of Service“ link at the Site. Use of the Services is not authorized in any jurisdiction that does not give effect to all provisions of these Terms of Service, including without limitation, this section. You agree that a printed version of these Terms of Service and other agreements entered into by you on the Site in electronic form will be admissible in judicial or administrative proceedings to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
    </Policy>
  );
};
export default TermsPage;

const Policy = styled.div`
  color: #eee;
  font-weight: 300;
  & > h1,
  & > h2,
  & > h3,
  & > h4 {
    font-weight: 400;
    color: #fff;
  };
  & > ul,
  & > ul > li > ul {
    list-style: disc;
  }
  & > code > *,
  & > pre > * {
    font-family: Courier, sans-serif;
  }
`;