import { TZSTATS_API_URL } from '.';

const allAliases = {
  tz1W1qbXXJrtLWwaaoXhe8LYGZqmNnpKaH9q: { name: '01Node' },
  tz1WBfwbT66FC6BTLexc2BoyCCBM9LG7pnVW: { name: '888XTZ' },
  tz1iLbZZ9uoRuVJCrZ9ZwiJMpfzhy3c67mav: { name: 'AirBie' },
  tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA: { name: 'Airfoil' },
  tz1QH3G2btaWc1vRLNsEfx2gHM7Ad81TeRit: { name: 'Airfoil Payouts', from: 'tz1gk3TDbU7cJuiBRMhwQXVvgDnjsxuWhcEA' },
  tz1MJx9vhaNRSimcuXPK2rW4fLccQnDAnVKJ: { name: 'AirGap' },
  tz1XhnCdVENzgko5x1MMswLHSoQbJ5NPwLZ6: { name: 'Anonstake' },
  tz3e75hU4EhDU3ukyJueh5v6UvEHzGwkg3yC: { name: 'At James' },
  tz1ZcTRk5uxD86EFEn1vvNffWWqJy7q5eVhc: { name: 'ATEZA' },
  tz1TqU5hwh6CtC8Ps5GYBi7YyawvtKLNCbvQ: { name: 'ATEZA Payouts', from:'tz1ZcTRk5uxD86EFEn1vvNffWWqJy7q5eVhc' },
  tz1KksC8RvjUWAbXYJuNrUbontHGor26Cztk: { name: 'Bakednode' },
  tz1aRhFErGMgL57DYHMT1vYwv7PzsJN1chrk: { name: 'Baked Tezos' },
  tz1Z1WwoqgRFbLE3YNdYRpCx44NSfiMJzeAG: { name: 'Bakemon' },
  tz1NkFRjmkqqcGkAhqe78fdgemDNKXvL7Bod: { name: 'BakeMyStake' },
  tz1WtkJEkKjHX3bMDYwJoDVC4gPksNPUa3v7: { name: 'BakeMyStake Legacy' },
  tz1NortRftucvAkD1J58L32EhSVrQEWJCEnB: { name: "Bake'n'Rolls" },
  tz1Zrqm4TkJwqTxm5TiyVFh6taXG4Wrq7tko: { name: "Bake'n'Rolls Payouts 1", from: 'tz1NortRftucvAkD1J58L32EhSVrQEWJCEnB' },
  KT1RCAETpkm9z44MW7Cph3mrWshqVURPubT4: { name: "Bake'n'Rolls Payouts 2", from: 'tz1NortRftucvAkD1J58L32EhSVrQEWJCEnB' },
  tz1YgNQBeLTgbwRb7QiyvHrx7hwN7AUbdqpB: { name: 'Baker Avenue' },
  tz1cYufsxHXJcvANhvS55h3aY32a9BAFB494: { name: 'Bakery IL' },
  tz1iVCqjMRG7MfBoFnVjbLQyeLAeJQfLxXze: { name: 'Bakery IL Payouts', from: 'tz1cYufsxHXJcvANhvS55h3aY32a9BAFB494' },
  tz1ei4WtWEMEJekSv8qDnu9PExG6Q8HgRGr3: { name: 'Bake Tz' },
  tz1NRGxXV9h6SdNaZLcgmjuLx3hyy2f8YoGN: { name: 'Bake Tz For Me' },
  tz1NXjtXZzwVJLocUtts5VmQ9nEPJVotweZm: { name: 'BAKRRR' },
  tz1Pv7ha8wzAyRHkR9RahWapdopK1tt6nVz1: { name: 'Baking Co-operative' },
  tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1: { name: 'Baking Tacos' },
  tz1fJHFn6sWEd3NnBPngACuw2dggTv6nQZ7g: { name: 'Baking Team' },
  tz1PayLDWLg39fbkwKejnT3aijz4QEd5kgt3: { name: 'Baking Team Payouts', from: 'tz1fJHFn6sWEd3NnBPngACuw2dggTv6nQZ7g' },
  tz1UsFcWtY6BxchK1L9619oXBzy3C2JCrRut: { name: 'Baking Tezos 4U' },
  tz1SiPXX4MYGNJNDsRc7n8hkvUqFzg8xqF9m: { name: 'Binance' },
  tz1S8MNvuFEUsWgjHvi3AxibRBf388NhT1q2: { name: 'Binance Baker' },
  tz1eogbwM5NdoojKEvvSnjYGcJapZgADRK3m: { name: 'Binance Delegator' },
  tz1XXayQohB8XRXN7kMoHbf2NFwNiH3oMRQQ: { name: 'Bit Cat' },
  tz1KtGwriE7VuLwT3LwuvU9Nv4wAxP7XZ57d: { name: 'Bitfinex' },
  tz1LmaFsWRkjr7QMCx5PtV6xTUz3AmEpKQiF: { name: 'Blockpower Staking' },
  tz1d2EwsrmoCPmhNUjt7unCQ8a9RwVsVXEmd: { name: 'BTFD' },
  tz3bEQoFCZEEfZMskefZ8q8e4eiHH1pssRax: { name: 'Ceibo XTZ' },
  tz1coHzgoQYRu1Ezn5QChfFEjwTrBzGNQT6U: { name: 'Clutch Oven' },
  tz1NcoDFXMAfB26mpBhVrdSHmppyTeccT6Fi: { name: 'Coinbase Pro' },
  tz1Z7eWGw18LqUgRqmDqNZFQx7f8GEHXRfT8: { name: 'Coinbase 1' },
  tz1bDhCGNZLQw1QXgf6MCzo6EtAVSGkqEB11: { name: 'Coinbase 2' },
  tz1irJKkXS2DBWkU1NnmFQx1c1L7pbGg4yhk: { name: 'Coinbase Custody' },
  tz1dbfppLAAxXZNtf2SDps7rch3qfUznKSoK: { name: 'Coinhouse' },
  tz1SYq214SCBy9naR6cvycQsYcUGpBqQAE8d: { name: 'Coinone' },
  tz1eEnQhbwf6trb8Q8mPb2RaPkNk2rN7BKi8: { name: 'Cryptium Labs' },
  tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5: { name: 'Crypto Delegate' },
  tz1MyXTZmeMCM4yFnrER9LNYDZ9t2rHYDvcH: { name: 'Crypto Delegate Payouts', from: 'tz1Tnjaxk6tbAeC2TmMApPh8UsrEVQvhHvx5' },
  tz1NqKH9D5HdfvoEQssMS5Up13CVypVxLA1k: { name: 'Cypher-Baker' },
  tz1Lc87p6zRaDwzJs9kHvdpm7XzeWE8QTwVB: { name: 'Dashmaster' },
  KT1A13N5XXJLgD9rQ6BF6xg71yhNhQhrCxia: { name: 'Dashmaster Payouts', from: 'tz1Lc87p6zRaDwzJs9kHvdpm7XzeWE8QTwVB' },
  tz1ZRWFLgT9sz8iFi1VYWPfRYeUvUSFAaDao: { name: 'Delegated Capital' },
  tz1LsuPvP2u63nouVGAPi13AYqqB2VQjhoSF: { name: 'Drunk Tortuga Bakery' },
  tz1W1f1JrE7VsqgpUpj1iiDobqP5TixgZhDk: { name: 'Elite Tezos' },
  tz1PK8bNrfPbc73BtHH1A63jfU5UtbRFkvU4: { name: 'EON Staking' },
  tz1MXFrtZoaXckE41bjUCSjAjAap3AFDSr3N: { name: 'Everstake' },
  tz1Scdr2HsZiQjc7bHMeBbmDRXYVvdhjJbBh: { name: 'Figment Network' },
  tz1ZQppA6UerMz5CJtGvZmmB6z8L9syq7ixu: { name: 'First Block' },
  tz1TzaNn7wSQSP5gYPXCnNzBCpyMiidCq1PX: { name: "Flippin' Tacos" },
  KT1GJBSMRGApA2DnSivs73Fhau6dbfP1Sntd: { name: "Flippin' Tacos Payouts 1", from: 'tz1TzaNn7wSQSP5gYPXCnNzBCpyMiidCq1PX' },
  tz1TacosCtikEQCJWYDZZ9MuA42sVpbbKZFF: { name: "Flippin' Tacos Payouts 2", from: 'tz1TzaNn7wSQSP5gYPXCnNzBCpyMiidCq1PX' },
  tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9: { name: 'Foundation Baker 1' },
  tz3bvNMQ95vfAYtG8193ymshqjSvmxiCUuR5: { name: 'Foundation Baker 2' },
  tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8: { name: 'Foundation Baker 3' },
  tz3bTdwZinP8U1JmSweNzVKhmwafqWmFWRfk: { name: 'Foundation Baker 4' },
  tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV: { name: 'Foundation Baker 5' },
  tz3UoffC7FG7zfpmvmjUmUeAaHvzdcUvAj6r: { name: 'Foundation Baker 6' },
  tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K: { name: 'Foundation Baker 7' },
  tz3VEZ4k6a4Wx42iyev6i2aVAptTRLEAivNN: { name: 'Foundation Baker 8' },
  tz1P6kxtzRrJ8KfXE4kKqR1RBiSpEgimxN5o: { name: 'Fractalide' },
  tz1QLXqnfN51dkjeghXvKHkJfhvGiM5gK4tc: { name: 'FreshTezos' },
  tz1iXQ3rgNt3rNHt9iNTm2muQYg1Msw2faFq: { name: 'FreshTezos Payouts', from: 'tz1QLXqnfN51dkjeghXvKHkJfhvGiM5gK4tc' },
  tz1NpWrAyDL9k2Lmnyxcgr9xuJakbBxdq7FB: { name: 'Gate.io' },
  tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q: { name: 'Happy Tezos' },
  tz1acsihTQWHEnxxNz7EEsBDLMTztoZQE9SW: { name: 'Happy Tezos Payouts', from: 'tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q' },
  tz1KzSC1J9aBxKp7u8TUnpN8L7S65PBRkgdF: { name: 'HashQuark' },
  tz1SohptP53wDPZhzTWzDUFAUcWF6DMBpaJV: { name: 'Hayek Lab' },
  tz1gg5bjopPcr9agjamyu9BbXKLibNc2rbAq: { name: 'Hodl Farm' },
  tz1hodLFy8YDHtf1qJ3XH1gCyeXfwWEitkj9: { name: 'Hodl Farm Payouts', from: 'tz1gg5bjopPcr9agjamyu9BbXKLibNc2rbAq' },
  tz1Z3KCf8CLGAYfvVWPEr562jDDyWkwNF7sT: { name: 'Hot Stake' },
  tz1VHFxUuBhwopxC9YC9gm5s2MHBHLyCtvN1: { name: 'Hyper Blocks Pro' },
  tz1dp3tScJZy8Go3byPdioSujgDi5CdemiuZ: { name: 'iBakeTezos' },
  tz1ZePm7HyANf3P9hZfhmm8ShbrbCP1nYwT5: { name: 'iBakeTezos Payouts 1', from: 'tz1dp3tScJZy8Go3byPdioSujgDi5CdemiuZ' },
  tz1VQq41XksF8oJ4ntxbh99g5wrqcreVf7e1: { name: 'iBakeTezos Payouts 2', from: 'tz1dp3tScJZy8Go3byPdioSujgDi5CdemiuZ' },
  tz1Ryat7ZuRapjGUgsPym9DuMGrTYYyDBJoq: { name: 'Illuminarean' },
  tz1bRaSjKZrSrSeQHBDiCqjKXqtZYZM1t8FW: { name: 'Imma Baker' },
  tz1awXW7wuXy21c66vBudMXQVAPgRnqqwgTH: { name: 'Infinity Stones' },
  tz1ZTG13gkvouxSANka3HG3uys8C5gu3DPXZ: { name: 'Just a Baker' },
  tz1bDXD6nNSrebqmAnnKKwnX1QdePSMCj4MX: { name: 'Kraken 1' },
  tz1YpWsMwc4gSyjtxEF3JbmN6YrGiDidaSmg: { name: 'Kraken 2' },
  tz1gfArv665EUkSg2ojMBzcbfwuPxAvqPvjo: { name: 'Kraken Baker' },
  tz1aqcYgG6NuViML5vdWhohHJBYxcDVLNUsE: { name: 'LetzBake!' },
  tz1MTAmuFmKu3MoxnkVsMj7xvSScj6d83hu5: { name: 'LetzBake! Payouts', from: 'tz1aqcYgG6NuViML5vdWhohHJBYxcDVLNUsE' },
  tz1MkjfzHNF3kk7PMUDVsaTrF8iRD6fpHftR: { name: 'LuxBaker 🇱🇺' },
  tz1VmiY38m3y95HqQLjMwqnMS7sdMfGomzKi: { name: 'Lucid Mining' },
  KT1THshzbGq3NJfL8w9j3ppbUSCfy5tQvWch: { name: 'Lucid Mining Payouts 1', from: 'tz1VmiY38m3y95HqQLjMwqnMS7sdMfGomzKi' },
  tz1LsnEuv4fLsgxU9HJK21v8zHwcuBjb99Cd: { name: 'Lucid Mining Payouts 2', from: 'tz1VmiY38m3y95HqQLjMwqnMS7sdMfGomzKi' },
  tz1aEsrxrhTYNcg897HjSWnJ5yjR95pxVD1d: { name: 'Mama Baker' },
  tz1PWCDnz783NNGGQjEFFsHtrcK5yBW4E2rm: { name: 'Melange' },
  tz1cb8xcmJWcdVU7cNAd93MfEReorvP52P8x: { name: 'Mint Capital' },
  tz1NEKxGEHsFufk87CVZcrqWu8o22qh46GK6: { name: 'Money Every 3 Days' },
  tz1bd5Pn5DxPinvCtkeJmoneyYiLeUebvUa5: { name: 'Money Every 3 Days Payout', from: 'tz1NEKxGEHsFufk87CVZcrqWu8o22qh46GK6'},
  tz1egbN6RK2bM5vt4aAZw6r9j4nL8z49bPdS: { name: 'Money Every 3 Days Legacy' },
  tz1d6Fx42mYgVFnHUW8T8A7WBfJ6nD9pVok8: { name: 'MyTezosBaking' },
  tz1Y2ufHak4AcisVazSS1ymGgv4HAmFGagh5: { name: 'MyTezosBaking Payouts', from: 'tz1d6Fx42mYgVFnHUW8T8A7WBfJ6nD9pVok8' },
  tz1YdCPrYbksK7HCoYKDyzgfXwY16Fy9rrGa: { name: 'Norn Delegate' },
  tz1UuQ4HWDu3ALNRgAq94dX9MhqhQhnuY3gC: { name: 'OKEx Baker' },
  tz1X1fpAZtwQk94QXUgZwfgsvkQgyc2KHp9d: { name: 'ownBLOCK Legacy' },
  tz1hTFcQk2KJRPzZyHkCwbj7E1zY1xBkiHsk: { name: 'ownBLOCK' },
  tz1P2Po7YM526ughEsRbY4oR9zaUPDZjxFrb: { name: 'P2P Validator' },
  tz1MoonPbyMJSqMVsVwExgVc5egnv18CgSDq: { name: 'P2P Validator Payouts', from: 'tz1P2Po7YM526ughEsRbY4oR9zaUPDZjxFrb' },
  tz1Ldzz6k1BHdhuKvAtMRX7h5kJSMHESMHLC: { name: 'PayTezos' },
  tz1c9HEyZdAWXZCLE7h3KcZCyykjZr7VY3QM: { name: 'PayTezos Payouts', from: 'tz1Ldzz6k1BHdhuKvAtMRX7h5kJSMHESMHLC' },
  KT1JjzGWesNFaHv9iyBwLBzLyTpTZ3HeBf7o: { name: 'PayTezos Payouts Legacy', from: 'tz1Ldzz6k1BHdhuKvAtMRX7h5kJSMHESMHLC' },
  tz1Yju7jmmsaUiG9qQLoYv35v5pHgnWoLWbt: { name: 'Polychain Labs I' },
  tz2TSvNTh2epDMhZHrw73nV9piBX7kLZ9K9m: { name: 'Polychain Labs II' },
  tz1Vyuu4EJ5Nym4JcrfRLnp3hpaq1DSEp1Ke: { name: 'PoSBakerz' },
  tz1PYF2Fcqk7YjZGquNy8bFznhCLhyi9PpVz: { name: 'Sanka Network' },
  tz1V4qCyvPKZ5UeqdH14HN42rxvNPQfc9UZg: { name: "Shake 'n Bake" },
  tz1e2meErj7eEfXwqr7bDK6N1YatmLaugfMp: { name: 'Special Tezos Baking' },
  tz1ZuxNqUk7odhMC4Bfx2NXXeej9ReXKewa8: { name: 'SNZ Holding' },
  tz1MDKr36woXfVtrtXfV1ppPJERxPcm2wU6V: { name: 'StackTezos' },
  tz1MowoYvqgxhKToQMAmGgTtjfZcRfS733JY: { name: 'StakeBake' },
  tz1V2FYediKBAEaTpXXJBSjuQpjkyCzrTSiE: { name: 'Stake House' },
  tz2FCNBrERXtaTtNX6iimR1UJ5JSDxvdHM93: { name: 'Stake Fish' },
  tz1RCFbB9GpALpsZtu6J58sb74dm8qe6XBzv: { name: 'Staked' },
  tz1g8vkmcde6sWKaG2NN9WKzCkDM6Rziq194: { name: 'StakeNow' },
  tz1Ywgcavxq9D6hL32Q2AQWHAux9MrWqGoZC: { name: 'StakeNow Payouts', from: 'tz1g8vkmcde6sWKaG2NN9WKzCkDM6Rziq194' },
  tz1go7f6mEQfT2xX2LuHAqgnRGN6c2zHPf5c: { name: 'Stakery' },
  tz1gs78wrxS34XhGPECmN5fABKpEuhUGwAXS: { name: 'Stakery Payouts', from: 'tz1go7f6mEQfT2xX2LuHAqgnRGN6c2zHPf5c' },
  tz1WpeqFaBG9Jm73Dmgqamy8eF8NWLz9JCoY: { name: 'Staking Facilities' },
  tz1STeamwbp68THcny9zk3LsbG3H36DMvbRK: { name: 'StakingTeam' },
  tz1fvBC1cHJzPtUW3ZKd2GZDj7P4XVuLk9vW: { name: 'Steaker' },
  tz1dNVDWPf3Q59SdJqnjdnu277iyvReiRS9M: { name: 'Steak.and.Bake' },
  tz1LH4L6XYT2JNPhvWYC4Zq3XEiGgEwzNRvo: { name: 'Stir Delegate' },
  tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6: { name: 'Tez Baker' },
  KT1TUi7KGFcTLku6niB2iGqzkv49ZLYxLRy1: { name: 'Tez Baker Payouts 1', from: 'tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6' },
  KT1Q6YAVkqcEmXAM7SUcQS9YSbLwbqMaVe3Z: { name: 'Tez Baker Payouts 2', from: 'tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6' },
  KT1KcLH9Qz6QJucvajEdXQvcSHgxfwuwDjNe: { name: 'Tez Baker Payouts 3', from: 'tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6' },
  KT1V86WP8CuxAtQ4xkpZ5fVtXv5XzK2F81mp: { name: 'Tez Baker Payouts 4', from: 'tz1Lhf4J9Qxoe3DZ2nfe8FGDnvVj7oKjnMY6' },
  tz1LBEKXaxQbd5Gtzbc1ATCwc3pppu81aWGc: { name: 'Tez Baking' },
  tz1NXPdPC2DfyA5ohitnS6ryqrDKbFJeu5Nn: { name: 'Tez Boss' },
  tz2LBtbMMvvguWQupgEmtfjtXy77cHgdr5TE: { name: 'Tezcentral' },
  tz1Yc6ATtfUJyDjHwJ8WoVL22sJueDenueke: { name: 'Tez Dele Baker A' },
  tz1SdwBHocSrcuMFNLPUg4LPRfx9eaqjVUEL: { name: 'Tez Dele Baker B' },
  tz1VceyYUpq1gk5dtp6jXQRtCtY8hm5DKt72: { name: 'TeZetetic' },
  tz1MQJPGNMijnXnVoBENFz9rUhaPt3S7rWoz: { name: 'Tez Mania' },
  tz1bakeKFwqmtLBzghw8CFnqFvRxLj849Vfg: { name: 'Tez Milk' },
  tz1W5VkdB5s7ENMESVBtwyt9kyvLqPcUczRT: { name: 'Tezgate' },
  tz1g4o4a2wxpzJ7EgG3onFM5TLaPyiRFjFhL: { name: 'Tezgate Payouts', from: 'tz1W5VkdB5s7ENMESVBtwyt9kyvLqPcUczRT' },
  tz1TaLYBeGZD3yKVHQGBM857CcNnFFNceLYh: { name: 'Tezocracy' },
  KT1CthjeJp2pLbSdo6xZR1VfgUD44QYDNmSZ: { name: 'Tezocracy Payouts 1', from: 'tz1TaLYBeGZD3yKVHQGBM857CcNnFFNceLYh' },
  tz1hfXvfcbbfcA77U8RXn7xLbRn3NHU4ksU1: { name: 'Tezocracy Payouts 2', from: 'tz1TaLYBeGZD3yKVHQGBM857CcNnFFNceLYh' },
  tz1PriNQyDC7d5ccPAD96ugujYy5YbdGLdQ5: { name: 'Tezos Baker JP' },
  tz1fZ767VDbqx4DeKiFswPSHh513f51mKEUZ: { name: 'Tezos Bakery' },
  tz1PYLN9TsKZHfn2GtrXnxkeGvahmYdBTG5v: { name: 'Tezos Bakes II' },
  tz1b2mCFQm8isfJRGUctgyxHhHcmTNTRPdps: { name: 'Tezos Barcelona' },
  tz1YvG6poSGhPLTdzbzCmqShMndzoyhyVg7J: { name: 'Tezos Baking Club' },
  tz1c3Wh8gNMMsYwZd67JndQpYxdaaPUV27E7: { name: 'TezosBC' },
  tz1QGZ3dD2YpRKZ4APeso6EXTeyCUUkw6MQC: { name: 'TezosBC Legacy' },
  KT1E5rWDHRA679Q98Tks3DppCqvBLUzmnBEe: { name: 'TezosBC Payouts', from: 'tz1c3Wh8gNMMsYwZd67JndQpYxdaaPUV27E7' },
  tz1RSWMYKGAykpizFteowByYMueCYv9TMn1L: { name: 'Tezos Alliance' },
  tz1YKh8T79LAtWxX29N5VedCSmaZGw9LNVxQ: { name: 'Tezos Brazil' },
  tz1aKxnrzx5PXZJe7unufEswVRCMU9yafmfb: { name: 'Tezos Canada' },
  tz2PdGc7U5tiyqPgTSgqCDct94qd6ovQwP6u: { name: 'Tezos Capital' },
  tz1TDSmoZXwVevLTEvKCTHWpomG76oC9S2fJ: { name: 'Tezos Capital Legacy' },
  tz1hThMBD8jQjFt78heuCnKxJnJtQo9Ao25X: { name: 'Tezos Chef' },
  tz1aCJuxfZPsXZ3PmfA6MvjsRTpGVVDMmb8X: { name: 'Tezos Chef Payouts', from: 'tz1hThMBD8jQjFt78heuCnKxJnJtQo9Ao25X' },
  tz1YTyvABUyhE7JHpxMVBVqjZnZM4ofMrWKE: { name: 'Tezos Delegate EU' },
  tz1U638Z3xWRiXDDKx2S125MCCaAeGDdA896: { name: 'Tezos France' },
  tz1TAzNBtnq6vF6kg34ApectxXoxZVTyapq3: { name: 'Tezos Gold' },
  tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8: { name: 'TezosHODL' },
  tz1TzHDLTNK1J1fCotGBLuE43DoogC5pHGyT: { name: 'TezosHODL Payouts', from: 'tz1WnfXMPaNTBmH7DBPwqCWs9cPDJdkGBTZ8' },
  tz1bLwpPfr3xqy1gWBF4sGvv8bLJyPHR11kx: { name: 'Tezos Hot Bakery' },
  tz1Vm5cfHncKGBo7YvZfHc4mmudY4qpWzvSB: { name: 'Tezos Istanbul' },
  tz1MBERDzXMvMQPCMWBCEgxyKrdU71HgXaM8: { name: 'Tezos Istanbul Payouts 1', from: 'tz1Vm5cfHncKGBo7YvZfHc4mmudY4qpWzvSB' },
  tz1Uf4Raxz7JzNdpAyM3893qLtqTRwNrdKVK: { name: 'Tezos Istanbul Payouts 2', from: 'tz1Vm5cfHncKGBo7YvZfHc4mmudY4qpWzvSB' },
  tz1b7YSEeNRqgmjuX4d4aiai2sQTF4A7WBZf: { name: 'Tezos Japan Legacy' },
  tz1ijdEfmUoQXJfSiKCLRioeCfSrKP3sVsff: { name: 'Tezos Japan' },
  tz1Nn14BBsDULrPXtkM9UQeXaE4iqJhmqmK5: { name: 'Tezos Kitchen' },
  tz1PPUo28B8BroqmVCMMNDudG4ShA2bzicrU: { name: 'Tezos Korea' },
  tz1Z1tMai15JWUWeN2PKL9faXXVPMuWamzJj: { name: 'TezosLand' },
  tz1S1Aew75hMrPUymqenKfHo8FspppXKpW7h: { name: 'Tezos Mars' },
  tz1TgvirXEwVJPg1cCrxT9zFubdzw7Ng6Ke9: { name: 'Tezos Moon' },
  tz1b3SaPHFSw51r92ARcV5mGyYbSSsdFd5Gz: { name: 'Tezos MX' },
  tz1eFXLaCUcKbhXkLBGUGMGNY9tKHjWGG25V: { name: 'Tezos Node Spain' },
  tz1djEKk6j1FqigTgbRsunbnY9BB7qsn1aAQ: { name: 'Tezos Ninja' },
  tz1fb7c66UwePkkfDXz4ajFaBP9hVNLdS7JJ: { name: 'Tezos NU' },
  tz1SkU5S3dDRi6f8LHCvYeK3H3Mjq4MS8uHW: { name: 'Tezos OTC' },
  tz1PeZx7FXy7QRuMREGXGxeipb24RsMMzUNe: { name: 'Tezos Panda' },
  KT1PnRgUjx7dD4xrnXnpJHz9MfnCWoeT6UBr: { name: 'Tezos Panda Payouts', from: 'tz1PeZx7FXy7QRuMREGXGxeipb24RsMMzUNe' },
  tz1b9MYGrbN1NAxphLEsPPNT9JC7aNFc5nA4: { name: 'Tezos R Us' },
  tz1cZfFQpcYhwDp7y1njZXDsZqCrn2NqmVof: { name: 'Tezos Rio' },
  tz1gfipKzYrNRT14oSNQJMCdRRsUtcbZoKsd: { name: 'Tezos Rio Legacy' },
  tz1R6Ej25VSerE3MkSoEEeBjKHCDTFbpKuSX: { name: 'TezosSEAsia' },
  tz1V3yg82mcrPJbegqVCPn6bC8w1CSTRp3f8: { name: 'TezoShop' },
  tz1Kf25fX1VdmYGSEzwFy1wNmkbSEZ2V83sY: { name: 'Tezos Seoul' },
  tz1Lh9jeLSWDHYy8AshvG2dpNQseDaHg7cms: { name: 'Tezos Spanish' },
  tz1hAYfexyzPGG6RhZZMpDvAHifubsbb6kgn: { name: 'Tezos Suisse' },
  tz1bkKTY9Y3rTsHbpr2fbGUCRm736LLquQfM: { name: 'Tezos Tacos' },
  tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA: { name: 'TezosTeam' },
  tz1YrmJw6Lje27gWqZ94gU9mNavEjkHu1xGc: { name: 'TezosTeam Payouts', from: 'tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA' },
  tz1VYQpZvjVhv1CdcENuCNWJQXu1TWBJ8KTD: { name: 'Tezos Tokyo' },
  tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca: { name: 'Tezos Vote' },
  tz1ggJg924JdWdww6oLGFksRgKctfrDMUNfE: { name: 'Tezos Vote Payouts', from: 'tz1bHzftcTKZMTZgLLtnrXydCm6UEqf4ivca' },
  tz1WctSwL49BZtdWAQ75NY6vr4xsAx6oKdah: { name: "Tezos Wake n' Bake" },
  tz1UUgPwikRHW1mEyVZfGYy6QaxrY6Y7WaG5: { name: 'TezPatisserie' },
  tz1YhNsiRRU8aHNGg7NK3uuP6UDAyacJernB: { name: 'Tez Baguette' },
  tz1abTjX2tjtMdaq5VCzkDtBnMSCFPW2oRPa: { name: 'Tez Rocket' },
  tz1UJvHTgpVzcKWhTazGxVcn5wsHru5Gietg: { name: 'Tezry' },
  tz1Vtimi84kLh9RANfRVX2JvYtP4NPCT1aFm: { name: 'TezTech Labs' },
  tz1isXamBXpTUgbByQ6gXgZQg4GWNW7r6rKE: { name: 'Tez Whale' },
  tz1WHALEgzq8cUUkg1vBKrpQrg9mysEX9NYR: { name: 'Tez Whale Payouts 1', from: 'tz1isXamBXpTUgbByQ6gXgZQg4GWNW7r6rKE' },
  tz1WHALEP56kjCTuUFLWjcBkfFpyevC4xo3t: { name: 'Tez Whale Payouts 2', from: 'tz1isXamBXpTUgbByQ6gXgZQg4GWNW7r6rKE' },
  tz1Zcxkfa5jKrRbBThG765GP29bUCU3C4ok5: { name: 'Tezz City' },
  tz1dhwJY5B1jKdkF7zcyu1v6EBEQjpGmAp1E: { name: 'Tezzz' },
  tz1ZjWs3FCrVnZ5ksszMi6cg9BWeo1Eb1nnm: { name: 'Tezzz Payouts', from: 'tz1dhwJY5B1jKdkF7zcyu1v6EBEQjpGmAp1E' },
  tz1fUjvVhJrHLZCbhPNvDRckxApqbkievJHN: { name: 'Tezzieland' },
  tz1WntXgznbivRjyhE7Y5jEzoebAhMPB2iJa: { name: 'Tezzieland Payouts', from: 'tz1fUjvVhJrHLZCbhPNvDRckxApqbkievJHN' },
  tz3adcvQaKXTCg12zbninqo3q8ptKKtDFTLv: { name: 'Tezzigator' },
  tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY: { name: 'Tezzigator Legacy' },
  tz1Yh1nLXfwqVpP8btykuRguu61n3veVmADa: { name: 'TzBakeOven' },
  tz1cX93Q3KsiTADpCC4f12TBvAmS5tw7CW19: { name: 'Tz Bakery' },
  tz1Zhv3RkfU2pHrmaiDyxp7kFZpZrUCu1CiF: { name: 'TzBake' },
  tz1bkg7rynMXVcjomoe3diB4URfv8GU2GAcw: { name: 'Tz Bank' },
  tz1PesW5khQNhy4revu2ETvMtWPtuVyH2XkZ: { name: 'TzDutch' },
  tz1iJ4qgGTzyhaYEzd1RnC6duEkLBd1nzexh: { name: 'Tz Envoy' },
  tz1Vd1rXpV8hTHbFXCXN3c3qzCsgcU5BZw1e: { name: 'TzNode' },
  tz1Pwgj6j55akKCyvTwwr9X4np1RskSXpQY4: { name: 'Validators' },
  tz1aiYKXmSRckyJ9EybKmpVry373rfyngJU8: { name: 'View Nodes' },
  tz1iMAHAVpkCVegF9FLGWUpQQeiAHh4ffdLQ: { name: 'Wetez' },
  tz1LesY3S4wfe15SNm1W3qJmQzWxLqVjTruH: { name: 'Xtez' },
  tz1TcH4Nb3aHNDJ7CGZhU7jgAK1BkSP4Lxds: { name: 'XTZ Antipodes' },
  tz1ZKi4VrDMEQpypn2NTn9pPbZL3xLRkETLA: { name: 'XTZ Baker' },
  tz1P9GwUWeAyPoT3ZwBc6gWCTP9exEPaVU3w: { name: 'XTZ Bakery' },
  tz1TnYeuR4HhUTapQiXvzcjmcpvZYwR1B5S3: { name: 'XTZ Bakery II' },
  tz1Suih9uWEnubDeqCTCEfueSCGWYohjyaA5: { name: 'XTZ Black' },
  tz1Xek93iSXXckyQ6aYLVS5Rr2tge2en7ZxS: { name: 'XTZ Delegate' },
  tz1KfEsrtDaA1sX7vdM4qmEPWuSytuqCDp5j: { name: 'XTZ Master' },
  tz1XTZMBAARXu3zmFno6SMT88MvqSvbD5qrh: { name: 'XTZ Master Payouts', from: 'tz1KfEsrtDaA1sX7vdM4qmEPWuSytuqCDp5j' },
  tz1Q8QkSBS63ZQnH3fBTiAMPes9R666Rn6Sc: { name: 'Yield Wallet' },
  tz1eZwq8b5cvE2bPKokatLkVMzkxz24z3Don: { name: 'You Loaf We Bake' },
  tz1L3vFD8mFzBaS8yLHFsd7qDJY1t276Dh8i: { name: 'Zed Node' },
  tz1KtvGSYU5hdKD288a1koTBURWYuADJGrLE: { name: 'ØCrypto Pool' },
  // well-known contracts/accounts
  tz1VwmmesDxud2BJEyDKUTV5T5VEP8tGBKGD: { name: 'Tezos Faucet' },
  tz1WcCGBxxPq61ddkp8X7vYMrWsBFMCxe5RD: { name: 'Fight COVID-19' },
  KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn: { name: 'tzBTC', token_type: 'tzbtc', bigmap_id: 31, },
  KT1QeoDkCAdJSSnm7zWz6Nv7W82qaoUz7kC9: { name: 'tzBTC Keyholder Owner', token_type: 'multisig' },
  KT1FcmdSroia1ys1WM6mL2rzB1haLxyy3MH9: { name: 'tzBTC Keyholder Operator', token_type: 'multisig' },
  KT1LH2o12xVRwTpJMZ6QJG74Fox8gE9QieFd: { name: 'tzBTC Test', token_type: 'tzbtc', bigmap_id: 446, net: 'NetXUdfLh6Gm88t' },
  KT1NCuMkcRrGDSiB5BX4xyBGEUtyyF7YDDYz: { name: 'tzBTC Test', token_type: 'tzbtc', bigmap_id: 518, txfn: '__entry_13__', net: 'NetXUdfLh6Gm88t' },
  KT1VG2WtYdSWz5E7chTeAdDPZNy2MpP8pTfL: { name: 'Atomex', token_type: 'atomex', bigmap_id: 4, txfn: 'redeem' },
  KT1EctCuorV2NfVb1XTQgvzJ88MQtWP8cMMv: { name: 'StakerDAO', token_type: 'sdao', bigmap_id: 20, txfn: 'transfer' },
  KT1BvVxWM6cjFuJNet4R9m64VDCN2iMvjuGE: { name: 'Tez-Baking Token', token_type: 'dab' },
  KT1ChNsEFxwyCbJyWGSL3KdjeXE28AY1Kaog: { name: 'Baker Registry', token_type: 'breg', utf8: true },
  KT1RM4Nzwe9kgyiF3WpqPdUezJ2SS7ixUdHX: { name: 'Trianon STO Issuer', token_type: 'nyx_issuer' },
  KT1XHAmdRKugP1Q38CxDmpcRSxq143KpEiYx: { name: 'Trianon STO Token', token_type: 'nyx_token' },
  KT1U1JZaXoG4u1EPnhHL4R4otzkWc1L34q3c: { name: 'Trianon KYC Registrar', token_type: 'nyx_kyc' },
};

// works with /explorer/config and /explorer/chain objects
export function isMainnet(o) {
  return (o && o.chain_id === 'NetXdQprcVkpaWU') || TZSTATS_API_URL === "https://api.tzstats.com" || TZSTATS_API_URL === "https://api.staging.tzstats.com";
}

let __aliases = null;

export function getAliases(o) {
  if (!__aliases && o) {
    const net = isMainnet(o.chain_id) ? undefined : o.chain_id;
    __aliases = {};
    Object.keys(allAliases).forEach(key => {
      if (allAliases[key].net === net) {
        __aliases[key] = allAliases[key];
      }
    });
  }
  return __aliases || allAliases;
}

let payoutMap = null;

export function getPayoutAddresses(baker = []) {
  // lazy-create payout map
  if (!payoutMap) {
    payoutMap = new Map();
    const aliases = getAliases();
    Object.keys(aliases).forEach(key => {
      const desc = aliases[key];
      if (desc.from) {
        let arr = payoutMap.get(desc.from)||[];
        arr.push(key);
        payoutMap.set(desc.from, arr);
      }
    });
  }
  // ensure we handle an array as input
  baker = Array.isArray(baker)?baker:[baker];
  if (!baker.length) {
    return Array.from(payoutMap.values()).flat();
  }
  let payouts = [];
  baker.forEach(b => {
    payouts.push(b);                         // add the baker address
    payouts.push(...(payoutMap.get(b)||[])); // add payout addresses
  });
  return payouts
}