// @flow
import { Colors } from '@blueprintjs/core';

export default {
  BLACK: Colors.BLACK,

  BLUE1: Colors.BLUE1,
  BLUE2: Colors.BLUE2,
  BLUE3: Colors.BLUE3,
  BLUE4: Colors.BLUE4,
  BLUE5: Colors.BLUE5,

  COBALT1: Colors.COBALT1,
  COBALT2: Colors.COBALT2,
  COBALT3: Colors.COBALT3,
  COBALT4: Colors.COBALT4,
  COBALT5: Colors.COBALT5,

  DARK_GRAY1: Colors.DARK_GRAY1,
  DARK_GRAY2: Colors.DARK_GRAY2,
  DARK_GRAY3: Colors.DARK_GRAY3,
  DARK_GRAY4: Colors.DARK_GRAY4,
  DARK_GRAY5: Colors.DARK_GRAY5,

  FOREST1: Colors.FOREST1,
  FOREST2: Colors.FOREST2,
  FOREST3: Colors.FOREST3,
  FOREST4: Colors.FOREST4,
  FOREST5: Colors.FOREST5,

  GOLD1: Colors.GOLD1,
  GOLD2: Colors.GOLD2,
  GOLD3: Colors.GOLD3,
  GOLD4: Colors.GOLD4,
  GOLD5: Colors.GOLD5,

  GRAY1: Colors.GRAY1,
  GRAY2: Colors.GRAY2,
  GRAY3: Colors.GRAY3,
  GRAY4: Colors.GRAY4,
  GRAY5: Colors.GRAY5,

  GREEN1: Colors.GREEN1,
  GREEN2: Colors.GREEN2,
  GREEN3: Colors.GREEN3,
  GREEN4: Colors.GREEN4,
  GREEN5: Colors.GREEN5,

  INDIGO1: Colors.INDIGO1,
  INDIGO2: Colors.INDIGO2,
  INDIGO3: Colors.INDIGO3,
  INDIGO4: Colors.INDIGO4,
  INDIGO5: Colors.INDIGO5,

  LIGHT_GRAY1: Colors.LIGHT_GRAY1,
  LIGHT_GRAY2: Colors.LIGHT_GRAY2,
  LIGHT_GRAY3: Colors.LIGHT_GRAY3,
  LIGHT_GRAY4: Colors.LIGHT_GRAY4,
  LIGHT_GRAY5: Colors.LIGHT_GRAY5,

  LIME1: Colors.LIME1,
  LIME2: Colors.LIME2,
  LIME3: Colors.LIME3,
  LIME4: Colors.LIME4,
  LIME5: Colors.LIME5,

  ORANGE1: Colors.ORANGE1,
  ORANGE2: Colors.ORANGE2,
  ORANGE3: Colors.ORANGE3,
  ORANGE4: Colors.ORANGE4,
  ORANGE5: Colors.ORANGE5,

  RED1: Colors.RED1,
  RED2: Colors.RED2,
  RED3: Colors.RED3,
  RED4: Colors.RED4,
  RED5: Colors.RED5,

  ROSE1: Colors.ROSE1,
  ROSE2: Colors.ROSE2,
  ROSE3: Colors.ROSE3,
  ROSE4: Colors.ROSE4,
  ROSE5: Colors.ROSE5,

  SEPIA1: Colors.SEPIA1,
  SEPIA2: Colors.SEPIA2,
  SEPIA3: Colors.SEPIA3,
  SEPIA4: Colors.SEPIA4,
  SEPIA5: Colors.SEPIA5,

  TURQUOISE1: Colors.TURQUOISE1,
  TURQUOISE2: Colors.TURQUOISE2,
  TURQUOISE3: Colors.TURQUOISE3,
  TURQUOISE4: Colors.TURQUOISE4,
  TURQUOISE5: Colors.TURQUOISE5,

  VERMILION1: Colors.VERMILION1,
  VERMILION2: Colors.VERMILION2,
  VERMILION3: Colors.VERMILION3,
  VERMILION4: Colors.VERMILION4,
  VERMILION5: Colors.VERMILION5,

  VIOLET1: Colors.VIOLET1,
  VIOLET2: Colors.VIOLET2,
  VIOLET3: Colors.VIOLET3,
  VIOLET4: Colors.VIOLET4,
  VIOLET5: Colors.VIOLET5,
  WHITE: Colors.WHITE,

  PRIMARY: Colors.BLUE5,
  SUCCESS: Colors.GREEN3,
  WARNING: Colors.ORANGE3,
  DANGER: Colors.RED3,
};
